In [1]:
import numpy as np

In [2]:
y = np.random.randint(0,56,(6,6))
print(y)

[[48 15 42 46 17 11]
 [ 7 17 46 13 51  5]
 [50 15 41 42 13 45]
 [27 43 14 23 38 45]
 [47 52 31 28 14 11]
 [31 29 43  8 28 50]]


In [3]:
print(y[0,3:5])

[46 17]


In [4]:
print(y[:,2])

[42 46 41 14 31 43]


In [5]:
print(y[2::2,::2])

[[50 41 13]
 [47 31 14]]


In [6]:
print(y[4:,4:])

[[14 11]
 [28 50]]
