In [1]:
import numpy as np

In [2]:
x = np.random.randint(10,30,10)
print(x)

[22 15 19 27 25 11 24 22 24 28]


In [3]:
y = np.sort(x)
print(y)

[11 15 19 22 22 24 24 25 27 28]


In [4]:
x2 = np.random.randint(10,20,(4,3))
print(x2)

[[14 16 13]
 [10 10 18]
 [11 17 12]
 [11 13 13]]


In [5]:
y2 = np.sort(x2) #satır bazlı sıralama yapar
print(y2)

[[13 14 16]
 [10 10 18]
 [11 12 17]
 [11 13 13]]


In [7]:
y3 = np.sort(x2,axis=0)  #sütun bazlı sıralama yapar
print(y3)

[[10 10 12]
 [11 13 13]
 [11 16 13]
 [14 17 18]]


In [11]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
print(a+5)
print(a-3)
print(a*3)
print(a/2)
print(a**2)

[ 6  7  8  9 10 11 12 13 14 15]
[-2 -1  0  1  2  3  4  5  6  7]
[ 3  6  9 12 15 18 21 24 27 30]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[  1   4   9  16  25  36  49  64  81 100]


In [14]:
q = np.array([10,20,30])
p = np.array([3,4,5])
print(np.add(q,p))

[13 24 35]


In [15]:
print(np.subtract(q,p))

[ 7 16 25]


In [17]:
print(np.multiply(q,p))

[ 30  80 150]


In [18]:
print(np.power(q,p))

[    1000   160000 24300000]


In [19]:
dizi1 = np.random.randint(1,100,(4,3))
print(dizi1)

[[74 94 60]
 [17 77 59]
 [47  3 27]
 [23 95 76]]


In [22]:
print(dizi1.max())
print(dizi1.max(axis=0))
print(dizi1.max(axis=1))

95
[74 95 76]
[94 77 47 95]


In [23]:
print(dizi1.min())
print(dizi1.min(axis=0))
print(dizi1.min(axis=1))

3
[17  3 27]
[60 17  3 23]


In [25]:
print(dizi1.sum())
print(dizi1.sum(axis=0))
print(dizi1.sum(axis=1))

652
[161 269 222]
[228 153  77 194]


In [26]:
print(dizi1.mean())
print(dizi1.mean(axis=0))
print(dizi1.mean(axis=1))

54.333333333333336
[40.25 67.25 55.5 ]
[76.         51.         25.66666667 64.66666667]
