In [1]:
import numpy as np

In [3]:
dizi = np.arange(1,10)
print(dizi)
print(dizi.ndim)
print(dizi.size)

[1 2 3 4 5 6 7 8 9]
1
9


In [5]:
yDizi = dizi.reshape(3,3)
print(yDizi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
dizi1 = np.arange(1,11)
print(dizi1)
print(dizi1.ndim)
print(dizi1.size)

[ 1  2  3  4  5  6  7  8  9 10]
1
10


In [9]:
yDizi1 = dizi1.reshape(2,5)
print(yDizi1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
yDizi2 = np.random.randint(0,10,(4,3))
print(yDizi2)

[[7 5 2]
 [4 1 1]
 [4 8 2]
 [1 4 4]]


In [11]:
dizi2 = yDizi2.reshape(-1)
print(dizi2)

[7 5 2 4 1 1 4 8 2 1 4 4]


In [12]:
x = np.array([1,2,3])
y = np.array([4,5,6])
t = np.concatenate([x,y])
print(t)

[1 2 3 4 5 6]


In [14]:
x1 = np.random.randint(0,10,(3,4))
print(x1)
y1 = np.random.randint(0,10,(3,4))
print(y1)
t1 = np.concatenate([x1,y1])
print(t1)

[[3 3 6 9]
 [1 8 8 3]
 [9 9 9 2]]
[[7 7 9 3]
 [2 7 6 0]
 [8 4 3 9]]
[[3 3 6 9]
 [1 8 8 3]
 [9 9 9 2]
 [7 7 9 3]
 [2 7 6 0]
 [8 4 3 9]]


In [15]:
t2 = np.concatenate([x1,y1],axis=1)
print(t2)

[[3 3 6 9 7 7 9 3]
 [1 8 8 3 2 7 6 0]
 [9 9 9 2 8 4 3 9]]
