In [1]:
import numpy as np

In [6]:
x = np.arange(10,30)
print(x.size)
print(x)

20
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [5]:
print(x[0:4])

[10 11 12 13]


In [7]:
print(x[:4])

[10 11 12 13]


In [11]:
print(x[4:])

[14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [13]:
print(x[:10:3])

[10 13 16 19]


In [14]:
y = np.random.randint(0,10,(4,4))
print(y)

[[1 7 0 0]
 [0 7 4 9]
 [7 4 7 8]
 [4 3 0 8]]


In [15]:
print(y[1,:])

[0 7 4 9]


In [16]:
print(y[:,1])

[7 7 4 3]


In [17]:
print(y[:2,:3])

[[1 7 0]
 [0 7 4]]


In [18]:
print(y[:,0:2])

[[1 7]
 [0 7]
 [7 4]
 [4 3]]


In [19]:
print(y[y>4])

[7 7 9 7 7 8 8]
