Numpy Kütüphanesini Ekleme

In [ ]:
import numpy as np

Numpy dizisinin oluşturulması

In [ ]:
liste1 = [0,1,2,3,4,5,6,7,8,9]

listearray = np.array([0,1,2,3,4,5,6,7,8,9])

print("Python Listesi : ",liste1)

print("Numpy Dizisi : ",listearray)

Python Listesi :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy Dizisi :  [0 1 2 3 4 5 6 7 8 9]


Dizinin boyutunu bulmak : ndarray.ndim

1.   Liste öğesi
2.   Liste öğesi



In [1]:
listearray1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(listearray1.ndim)

listearray2 = np.array([[0,1,2,3,4,5,6,7,8,9]])
print(listearray2.ndim)

NameError: ignored

 Dizinin satır ve sütun sayısını bulmak: ndarray.shape

In [ ]:
listearray3 = np.array([0,1,2,3,4,5,6,7,8,9])
print(listearray3.shape)
print(listearray3.ndim)

listearray4 = np.array([[0,1,2,3,4,5,6,7,8,9]])
print(listearray4.ndim)
print(listearray4.shape)

(10,)
1
2
(1, 10)


Dizinin satır ve sütun sayısını değiştirmek : ndarray.reshape()

In [ ]:
listearray5 = np.array([0,1,2,3,4,5,6,7,8,9])
print(listearray5.reshape(1,10))

print(listearray5.reshape(10,1))

print(listearray5.reshape(5,2))

print(listearray5.reshape(2,5))

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


np.arange()

In [ ]:
listearange = np.arange(0,10,3)
print(listearange)

listearange2 = np.arange(10)
print(listearange2)

listearange3 = np.arange(0,10,1)
print(listearange3)

[0 3 6 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


Dizinin elemanlarını seçmek

In [ ]:
listesec = np.array([0,1,2,3,4,5,6,7,8,9])
print(listesec.reshape(5,2))

ilk = listesec[:2]
print(ilk)

ilkveiki = listesec[2:4]
print(ilkveiki)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1]
[2 3]


Diziyi ters çevirmek

In [ ]:
listeters = np.array([0,1,2,3,4,5,6,7,8,9])
listeters = listeters.reshape(5,2)
print(listeters)

print(listeters[::-1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


0 matrisi oluşturmak : np.zeros()

In [ ]:
print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
print(np.ones((3,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Birim matris oluşturmak : np.eye()

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Matrisleri birleştirmek

In [ ]:
matrixbirlik = np.array([0,1,2,3,4,5,6,7,8,9])
matrixbirlik = matrixbirlik.reshape(5,2)

print(np.concatenate([matrixbirlik, matrixbirlik], axis = 0))

print(np.concatenate([matrixbirlik,matrixbirlik], axis = 1))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


**Numpy ile Matematiksel İşlemler**

sum(toplam), max ve min değerlerini hesaplamak

In [ ]:
litetoplam = np.array([0,1,2,3,4,5,6,7,8,9])
litetoplam = litetoplam.reshape(5,2)
print(litetoplam)

print(litetoplam.max())

print(litetoplam.min())

print(litetoplam.sum())

print(litetoplam.sum(axis = 1))

print(litetoplam.sum(axis = 0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
9
0
45
[ 1  5  9 13 17]
[20 25]


mean, median, varyans ve standart sapma hesaplamak

In [ ]:
listemean = np.array([0,1,2,3,4,5,6,7,8,9])

print(listemean.mean()) # Mean = ortalama

print(np.median(listemean)) # Mean = median

print(listemean.var())

print(listemean.std()) # Ortalamadan uzaklığı

4.5
4.5
8.25
2.8722813232690143


Matrislerde aritmetik işlemler

In [ ]:
listematrixislem = np.array([1,2,3,4,5,6,7,8,9])
listematrixislem = listematrixislem.reshape(3,3)

print(listematrixislem)

print(listematrixislem + listematrixislem)

print(listematrixislem - listematrixislem)

print(listematrixislem * listematrixislem)

print(listematrixislem / listematrixislem)

print(listematrixislem + 5)

print(listematrixislem * 2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Özel foksiyonlar ile işlemler

In [ ]:
listeozel = np.array([1,2,3,4,5,6,7,8,9])
listeozel = listeozel.reshape(3,3)

print(np.sin(listeozel))

print(np.cos(listeozel))

print(np.sqrt(listeozel))

print(np.exp(listeozel))

print(np.log(listeozel))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


Matrislerin çarpımı

In [ ]:
matrixcarp = np.array([0,1,2,3,4,5,6,7,8,9])
matrixcarp1 = matrixcarp.reshape(5,2)
matrixcarp2 = matrixcarp.reshape(2,5)
print(np.dot(matrixcarp1,matrixcarp2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


Matrisin transpozu

In [ ]:
matrixtrans = np.array([0,1,2,3,4,5,6,7,8,9])
matrixtrans = matrixtrans.reshape(5,2)

print(matrixtrans)
print(matrixtrans.T)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


Numpy’da Koşul İfadeleri ile Çalışmak




In [ ]:
listekosul = np.array([0,1,2,3,4,5,6,7,8,9])
boolean_array = listekosul >= 5
print(boolean_array)

[False False False False False  True  True  True  True  True]


In [ ]:
print(listekosul[boolean_array])
print(listekosul<5)
print(listekosul[listekosul<5])

[5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
